name: Build and Push Docker image
on:
  push:
    branches:
      - main
    paths:
      - '**.ts'
      - '**.tsx'
      - 'vite.config.ts'
      - 'Dockerfile'
      - 'package.json'
      - 'package-lock.json'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/philipppollmann/telekom-project-launchpad/app:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=github.com/philipppollmann/Telekom-Project-Launchpad
            org.opencontainers.image.author=philipppollmann
